AllCops:
  DisabledByDefault: true
  Exclude:
    - 'gemfiles/**/*'

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  Enabled: true
  EnforcedStyle: double_quotes

Layout/SpaceBeforeBlockBraces:
  Enabled: true
  EnforcedStyle: 'space'

Layout/SpaceInsideArrayLiteralBrackets:
  Enabled: true

Layout/SpaceInsideReferenceBrackets:
  Enabled: true

Layout/SpaceInsideHashLiteralBraces:
  Enabled: true

Layout/SpaceInsideBlockBraces:
  Enabled: true

Layout/SpaceAroundEqualsInParameterDefault:
  Enabled: true

Layout/SpaceBeforeComma:
  Enabled: false

Layout/SpaceAroundOperators:
  Enabled: true

Layout/SpaceAfterComma:
  Enabled: true

Layout/ExtraSpacing:
  Enabled: true
  AllowForAlignment: true

Lint/DuplicateMethods:
  Enabled: true

Layout/LineLength:
  Enabled: true
  Max: 200
  AllowHeredoc: true
  AllowURI: true
  URISchemes: http, https

Metrics/MethodLength:
  Enabled: true
  Max: 25

Metrics/ClassLength:
  Enabled: true
  Max: 160

Metrics/ModuleLength:
  Enabled: true
  Max: 160

Style/ClassAndModuleChildren:
  EnforcedStyle: compact
  Exclude:
    - lib/sidekiq/merger/version.rb

Layout/ArrayAlignment:
  Enabled: true

Layout/HashAlignment:
  Enabled: true

Layout/BlockEndNewline:
  Enabled: false

Style/DoubleNegation:
  Enabled: false

Metrics/AbcSize:
  Max: 60

Metrics/CyclomaticComplexity:
  Max: 12

Metrics/PerceivedComplexity:
  Max: 12
